### ISSUE TITLE
BUG: Cause.reduceWithContext

### ISSUE THREAD

**Issue by joshamaju** [Effect-TS/effect#1571]
### What version of Effect is running?

2.0.0-next.50

### What steps can reproduce the bug?

const program = Effect.gen(function* (_) {
  const response = yield* _(
    Effect.tryPromise(() => fetch("https://reqres.in/api/users"))
  );

  const json = yield* _(Effect.tryPromise(() => response.json()));
  yield* _(Effect.log("result: ", json)); // Effect.log only accepts one parameter, but this cause the entire pipeline to error
  return json;
});

### What is the expected behavior?

The extra parameter shouldn't cause an error, or the stack trace should at least capture that. Rather than saying it's a bug in Effect code.

### What do you see instead?

```
{
  _id: 'FiberFailure',
  cause: {
    _id: 'Cause',
    _tag: 'Die',
    defect: Error: BUG: Cause.reduceWithContext - please report an issue at https://github.com/Effect-TS/io/issues
        at /Users/software/Desktop/Joshua/kit/node_modules/.pnpm/effect@2.0.0-next.50/node_modules/effect/dist/core-b4bf44d3.cjs.dev.js:1252:11
        at /Users/software/Desktop/Joshua/kit/node_modules/.pnpm/effect@2.0.0-next.50/node_modules/effect/Function/dist/effect-Function.cjs.dev.js:108:18
        at isInterruptedOnly (/Users/software/Desktop/Joshua/kit/node_modules/.pnpm/effect@2.0.0-next.50/node_modules/effect/dist/core-b4bf44d3.cjs.dev.js:600:94)
        at Object.pretty (/Users/software/Desktop/Joshua/kit/node_modules/.pnpm/effect@2.0.0-next.50/node_modules/effect/dist/core-b4bf44d3.cjs.dev.js:1360:7)
        at Object.log (/Users/software/Desktop/Joshua/kit/node_modules/.pnpm/effect@2.0.0-next.50/node_modules/effect/dist/fiberRuntime-0c1e7478.cjs.dev.js:183:32)
        at Object.log (/Users/software/Desktop/Joshua/kit/node_modules/.pnpm/effect@2.0.0-next.50/node_modules/effect/dist/fiberRuntime-0c1e7478.cjs.dev.js:2013:34)
        at FiberRuntime.log (/Users/software/Desktop/Joshua/kit/node_modules/.pnpm/effect@2.0.0-next.50/node_modules/effect/dist/fiberRuntime-0c1e7478.cjs.dev.js:1501:16)
        at EffectPrimitive.i0 (/Users/software/Desktop/Joshua/kit/node_modules/.pnpm/effect@2.0.0-next.50/node_modules/effect/dist/core-effect-f4b1aad8.cjs.dev.js:437:16)
        at FiberRuntime.WithRuntime (/Users/software/Desktop/Joshua/kit/node_modules/.pnpm/effect@2.0.0-next.50/node_modules/effect/dist/fiberRuntime-0c1e7478.cjs.dev.js:1816:15)
        at /Users/software/Desktop/Joshua/kit/node_modules/.pnpm/effect@2.0.0-next.50/node_modules/effect/dist/fiberRuntime-0c1e7478.cjs.dev.js:1973:28
  }
}
```

**Comment by mikearnaldi** [comment]
Expected behaviour, in this case the issue is that the parameter you're passing in is of type `any` so you're basically disabling type checking. The `Effect.log` function accepts an optional second parameter that is supposed to be of type `Cause<unknown>`.
