### ISSUE TITLE
Context not being removed by layer provide

### ISSUE THREAD

**Issue by nobletom123** [Effect-TS/effect#1771]
### What version of Effect is running?

2.0.0-next.55

### What steps can reproduce the bug?

Create a new project, and use this code (From the Effect website)

```
import { Effect, Layer, Console, Context } from "effect"

// Define the interface for the MeasuringCup service
export interface MeasuringCup {
  readonly measure: (
    amount: number,
    unit: string
  ) => Effect.Effect<never, never, string>
}
 
// Create a tag for the MeasuringCup service
export const MeasuringCup = Context.Tag<MeasuringCup>()
 
// $ExpectType Layer<never, never, MeasuringCup>
export const MeasuringCupLive = Layer.succeed(
  MeasuringCup,
  MeasuringCup.of({
    measure: (amount, unit) => Effect.succeed(`Measured ${amount} ${unit}(s)`)
  })
)

// Sugar
 
export interface Sugar {
  readonly grams: (amount: number) => Effect.Effect<never, never, string>
}
 
export const Sugar = Context.Tag<Sugar>()
 
// $ExpectType Layer<MeasuringCup, never, Sugar>
export const SugarLive = Layer.effect(
  Sugar,
  Effect.map(MeasuringCup, (measuringCup) =>
    Sugar.of({
      grams: (amount) => measuringCup.measure(amount, "gram")
    })
  )
)
 
// Flour
 
export interface Flour {
  readonly cups: (amount: number) => Effect.Effect<never, never, string>
}
 
export const Flour = Context.Tag<Flour>()
 
// $ExpectType Layer<MeasuringCup, never, Flour>
export const FlourLive = Layer.effect(
  Flour,
  Effect.map(MeasuringCup, (measuringCup) =>
    Flour.of({
      cups: (amount) => measuringCup.measure(amount, "cup")
    })
  )
)

export interface Recipe {
  readonly steps: Effect.Effect<never, never, ReadonlyArray<string>>
}
 
export const Recipe = Context.Tag<Recipe>()
 
// $ExpectType Layer<Sugar | Flour, never, Recipe>
export const RecipeLive = Layer.effect(
  Recipe,
  Effect.all([Sugar, Flour]).pipe(
    Effect.map(([sugar, flour]) =>
      Recipe.of({
        steps: Effect.all([sugar.grams(200), flour.cups(1)])
      })
    )
  )
)
 
// $ExpectType Layer<MeasuringCup, never, Sugar | Flour>
const IngredientsLive = Layer.merge(SugarLive, FlourLive)
 
// $ExpectType Layer<never, never, Recipe>
const MainLive = RecipeLive.pipe(
    Layer.provide(IngredientsLive),
    Layer.provide(MeasuringCupLive)
)
 
// $ExpectType Effect<Recipe, never, void>
const program = Recipe.pipe(
  Effect.flatMap((recipe) => recipe.steps),
  Effect.flatMap((steps) =>
    Effect.forEach(steps, (step) => Console.log(step), {
      concurrency: "unbounded",
      discard: true
    })
  )
)
 
// $ExpectType Effect<never, never, void>
const runnable = Effect.provide(program, MainLive)
 
Effect.runPromise(runnable)
/*
Output:
Measured 200 gram(s)
Measured 1 cup(s)
*/
```

### What is the expected behavior?

That I should be able to use Effect.runPromise with runnable without any type errors.

### What do you see instead?

A type error saying - 

```
Argument of type 'Effect<MeasuringCup | Sugar | Flour | Recipe, never, void>' is not assignable to parameter of type 'Effect<never, never, void>'.
  Type 'MeasuringCup | Sugar | Flour | Recipe' is not assignable to type 'never'.
    Type 'MeasuringCup' is not assignable to type 'never'.
```

When running (using ts-node), I get this error:

```
Error: Service not found (defined at Object.<anonymous> (/Users/brandgility/functional-testing/src/example/index.ts:28:30))
    at f (/Users/brandgility/functional-testing/node_modules/effect/src/internal/fiberRuntime.ts:1033:26)
    at EffectPrimitive.i0 (/Users/brandgility/functional-testing/node_modules/effect/src/internal/core.ts:942:51)
    at FiberRuntime.Sync (/Users/brandgility/functional-testing/node_modules/effect/src/internal/fiberRuntime.ts:1059:22)
    at f (/Users/brandgility/functional-testing/node_modules/effect/src/internal/fiberRuntime.ts:1304:53)
    at Object.context (/Users/brandgility/functional-testing/node_modules/effect/src/internal/tracer.ts:86:19)
    at FiberRuntime.runLoop (/Users/brandgility/functional-testing/node_modules/effect/src/internal/fiberRuntime.ts:1294:28)
    at FiberRuntime.evaluateEffect (/Users/brandgility/functional-testing/node_modules/effect/src/internal/fiberRuntime.ts:863:29)
/Users/brandgility/functional-testing/node_modules/effect/src/internal/fiberRuntime.ts:1033
          return Context.unsafeGet(context, op as unknown as Context.Tag<any, any>)
                         ^
Error: Service not found (defined at Object.<anonymous> (/Users/brandgility/functional-testing/src/example/index.ts:28:30))
Error: Service not found (defined at Object.<anonymous> (/Users/brandgility/functional-testing/src/example/index.ts:28:30))
    at f (/Users/brandgility/functional-testing/node_modules/effect/src/internal/fiberRuntime.ts:1033:26) {
  toJSON: [Function (anonymous)],
  toString: [Function (anonymous)],
  [Symbol(effect/Runtime/FiberFailure)]: Symbol(effect/Runtime/FiberFailure),
  [Symbol(effect/Runtime/FiberFailure/Cause)]: {
    _tag: 'Die',
    defect: Error: Service not found (defined at Object.<anonymous> (/Users/brandgility/functional-testing/src/example/index.ts:28:30))
        at f (/Users/brandgility/functional-testing/node_modules/effect/src/internal/fiberRuntime.ts:1033:26)
        at EffectPrimitive.i0 (/Users/brandgility/functional-testing/node_modules/effect/src/internal/core.ts:942:51)
        at FiberRuntime.Sync (/Users/brandgility/functional-testing/node_modules/effect/src/internal/fiberRuntime.ts:1059:22)
        at f (/Users/brandgility/functional-testing/node_modules/effect/src/internal/fiberRuntime.ts:1304:53)
        at Object.context (/Users/brandgility/functional-testing/node_modules/effect/src/internal/tracer.ts:86:19)
        at FiberRuntime.runLoop (/Users/brandgility/functional-testing/node_modules/effect/src/internal/fiberRuntime.ts:1294:28)
        at FiberRuntime.evaluateEffect (/Users/brandgility/functional-testing/node_modules/effect/src/internal/fiberRuntime.ts:863:29)
  },
  [Symbol(nodejs.util.inspect.custom)]: [Function (anonymous)]
}
```

### Additional information

Just started with effect, have followed the docs on building services / layers. Was getting a type error with my own implementation, have copied and pasted the implementation from the site, getting the same error. From the docs it looks like the context of each layer should be removed when the implementation of its dependencies is given, that doesn't seem to be happening though with the error?

**Comment by nobletom123** [comment]
Was not using latest version of package (2.0.0-next.55 as opposed to 2.0.0-next.60)
