### ISSUE TITLE
TimeoutOverflowWarning when using @effect/cli with a file argument

### ISSUE THREAD

**Issue by leonitousconforti** [Effect-TS/effect#1917]
### What version of Effect is running?

2.0.3

### What steps can reproduce the bug?

When using @effect/cli with a file argument, node prints:

```
(node:336148) TimeoutOverflowWarning: 9007199254740991 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```

repro with more information: <https://github.com/leonitousconforti/effect-TimeoutOverflowWarning-repro>

### What is the expected behavior?

For the timeout to not overflow? It doesn't seem to cause any noticeable issues for me, the cli still runs and completes though

### What do you see instead?

A warning about a timeout overflow from effect runMain

```
 (node:6365) TimeoutOverflowWarning: 9007199254740991 does not fit into a 32-bit signed integer.
 Timeout duration was set to 1.
     at new Timeout (node:internal/timers:169:17)
     at setInterval (node:timers:234:19)
     at runMain (/workspaces/effect-TimeoutOverflowWarning-repro/node_modules/.pnpm/@effect+platform-node@0.41.0_@effect+platform@0.41.0_effect@2.0.3/node_modules/@effect/platform-node/src/internal/runtime.ts:10:21)
     at pipeArguments (/workspaces/effect-TimeoutOverflowWarning-repro/node_modules/.pnpm/effect@2.0.3/node_modules/effect/src/Pipeable.ts:295:21)
     at pipe (/workspaces/effect-TimeoutOverflowWarning-repro/node_modules/.pnpm/effect@2.0.3/node_modules/effect/src/internal/core.ts:164:25)
     at <anonymous> (/workspaces/effect-TimeoutOverflowWarning-repro/bad.ts:19:50)
     at Object.<anonymous> (/workspaces/effect-TimeoutOverflowWarning-repro/bad.ts:22:1)
     at Module._compile (node:internal/modules/cjs/loader:1376:14)
     at Object.S (/workspaces/effect-TimeoutOverflowWarning-repro/node_modules/.pnpm/tsx@4.7.0/node_modules/tsx/dist/cjs/index.cjs:1:1292)
     at Module.load (node:internal/modules/cjs/loader:1207:32)
```

### Additional information

repro with more information: <https://github.com/leonitousconforti/effect-TimeoutOverflowWarning-repro>

**Comment by leonitousconforti** [comment]
ooops, thought I had searched discord and github for relevant terms well enough but I just came across https://github.com/Effect-TS/effect/pull/1905 when searching other places for MAX_SAFE_INTEGER
