### ISSUE TITLE
TaggedError does not construct properly

### ISSUE THREAD

**Issue by steffanek** [Effect-TS/effect#2183]
### What version of Effect is running?

2.3.7

### What steps can reproduce the bug?

I was writing, some unit tests using vitest and notice that some assertions were wrong, I started to debug and find out that those 2 assertions succeed:
```ts
 expect({ error: new DataTaggedError({ msg: "a" })}).toStrictEqual({error: new DataTaggedError({ msg: "b" })});
 expect({ error: new SchemaTaggedError({ msg: "a" })}).toStrictEqual({ error: new SchemaTaggedError({ msg: "b" })});
```
which is wrong.. 

so I logged to the console all class instances to compare them and got a weird response for `TaggedError` (both `Data` and `Schema` variants):

```ts
import { Schema } from "@effect/schema";
import { Data } from "effect";

class SchemaClass extends Schema.Class<SchemaClass>()({
  msg: Schema.string,
}) {}

const schemaClass = new SchemaClass({ msg: "a" });
console.log("schemaClass", schemaClass);

class SchemaTaggedClass extends Schema.TaggedClass<SchemaTaggedClass>()(
  "SchemaTaggedClass",
  {
    msg: Schema.string,
  }
) {}

const schemaTaggedClass = new SchemaTaggedClass({ msg: "a" });
console.log("schemaTaggedClass", schemaTaggedClass);

class DataTaggedClass extends Data.TaggedClass("DataTaggedClass")<{
  msg: string;
}> {}

const dataTaggedClass = new DataTaggedClass({ msg: "a" });
console.log("dataTaggedClass", dataTaggedClass);

class SchemaTaggedError extends Schema.TaggedError<SchemaTaggedError>()(
  "SchemaTaggedError",
  {
    msg: Schema.string,
  }
) {}

const schemaTaggedError = new SchemaTaggedError({ msg: "a" });
console.log("schemaTaggedError", schemaTaggedError); //BUG?: WEIRD the console...

class DataTaggedError extends Data.TaggedError("DataTaggedError")<{
  msg: string;
}> {}

const dataTaggedError = new DataTaggedError({ msg: "a" });
console.log("dataTaggedError", dataTaggedError); //BUG?: WEIRD the console...
```
The output looks as follow: 
```
schemaClass SchemaClass { msg: 'a' }
schemaTaggedClass SchemaTaggedClass { _tag: 'SchemaTaggedClass', msg: 'a' }
dataTaggedClass DataTaggedClass { msg: 'a', _tag: 'DataTaggedClass' }
schemaTaggedError SchemaTaggedError({ "_tag": "SchemaTaggedError", "msg": "a" })
    at <anonymous> (/test.ts:46:27)
    at Object.<anonymous> (/test.ts:54:47)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Object.S (/node_modules/.pnpm/tsx@4.7.0/node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async CustomizedModuleLoader.import (node:internal/modules/esm/loader:246:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
dataTaggedError DataTaggedError
    at <anonymous> (/test.ts:53:25)
    at Object.<anonymous> (/test.ts:54:47)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Object.S (/node_modules/.pnpm/tsx@4.7.0/node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async CustomizedModuleLoader.import (node:internal/modules/esm/loader:246:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
   ```

### What is the expected behavior?

 Those assertion should fail using vitest:
```ts
 expect({ error: new DataTaggedError({ msg: "a" })}).toStrictEqual({error: new DataTaggedError({ msg: "b" })});
 expect({ error: new SchemaTaggedError({ msg: "a" })}).toStrictEqual({ error: new SchemaTaggedError({ msg: "b" })});
 ```
 
 and it should log to the console:
 ```
schemaClass SchemaClass { msg: 'a' }
schemaTaggedClass SchemaTaggedClass { _tag: 'SchemaTaggedClass', msg: 'a' }
dataTaggedClass DataTaggedClass { msg: 'a', _tag: 'DataTaggedClass' }
schemaTaggedError SchemaTaggedError({ "_tag": "SchemaTaggedError", "msg": "a" })
dataTaggedError DataTaggedError ({ "_tag": "DataTaggedError", "msg": "a" })
```

### What do you see instead?

The output looks as follow:
```
schemaClass SchemaClass { msg: 'a' }
schemaTaggedClass SchemaTaggedClass { _tag: 'SchemaTaggedClass', msg: 'a' }
dataTaggedClass DataTaggedClass { msg: 'a', _tag: 'DataTaggedClass' }
schemaTaggedError SchemaTaggedError({ "_tag": "SchemaTaggedError", "msg": "a" })
    at <anonymous> (/test.ts:46:27)
    at Object.<anonymous> (/test.ts:54:47)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Object.S (/node_modules/.pnpm/tsx@4.7.0/node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async CustomizedModuleLoader.import (node:internal/modules/esm/loader:246:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
dataTaggedError DataTaggedError
    at <anonymous> (/test.ts:53:25)
    at Object.<anonymous> (/test.ts:54:47)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Object.S (/node_modules/.pnpm/tsx@4.7.0/node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async CustomizedModuleLoader.import (node:internal/modules/esm/loader:246:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
   ```

### Additional information

typescript 5.3.3
effect 2.3.7
@effect/schema 0.62.8
vitest 1.2.2

**Comment by gcanti** [comment]
The output is fine (they are errors, and that's the stack trace), but it seems like there's a bug in `expect`, using 

```ts
import * as assert from "node:assert"
```

works:

```ts
class DataTaggedError extends Data.TaggedError("DataTaggedError")<{
  msg: string
}> {}

// no error
expect({ error: new DataTaggedError({ msg: "a" }) }).toStrictEqual({ error: new DataTaggedError({ msg: "b" }) })

// error
assert.deepStrictEqual({ error: new DataTaggedError({ msg: "a" }) }, { error: new DataTaggedError({ msg: "b" }) })

class SchemaTaggedError extends S.TaggedError<SchemaTaggedError>()(
  "SchemaTaggedError",
  {
    msg: S.string
  }
) {}

// no error
expect({ error: new SchemaTaggedError({ msg: "a" }) }).toStrictEqual({ error: new SchemaTaggedError({ msg: "b" }) })

// error
assert.deepStrictEqual({ error: new SchemaTaggedError({ msg: "a" }) }, {
  error: new SchemaTaggedError({ msg: "b" })
})
```

**Comment by steffanek** [comment]
That's correct, and what's the reason that:
```ts
class DataTaggedError extends Data.TaggedError("DataTaggedError")<{
  msg: string;
}> {}

const dataTaggedError = new DataTaggedError({ msg: "a" });
console.log("dataTaggedError", dataTaggedError);
```
Output the following (without logging the instance?:
```
dataTaggedError DataTaggedError 
..stack trace..
```

**Comment by gcanti** [comment]
both are `YieldableError`s: https://github.com/Effect-TS/effect/blob/6612682a82392d14bd968f2760bd70b35f088f7e/packages/effect/src/internal/core.ts#L2253-L2259 so it depends on how `this.toString()` is implemented

**Comment by steffanek** [comment]
Thanks for your explanation and for pointing to the internal resource.
I will update and close this thread as soon as vitest will fixed the issue.

**Comment by steffanek** [comment]
I'm closing this issue. To make vitest expect work please follow this link:  [](https://github.com/vitest-dev/vitest/issues/5244)
