### ISSUE TITLE
Fiber Runtime - undefined

### ISSUE THREAD

**Issue by timsuchanek** [Effect-TS/effect#2253]
### What steps can reproduce the bug?

I'm calling Effect.forEach in a nested manner.
I don't have time right now to isolate a reproduction, but will invite @tim-smart @mikearnaldi in my private repo, where you can easily reproduce.

Invites and details coming.

### What is the expected behavior?

No error.

### What do you see instead?

timestamp=2024-03-05T12:17:55.785Z level=ERROR fiber=#0 cause="Error: BUG: FiberRuntime - undefined - please report an issue at https://github.com/Effect-TS/effect/issues
Error: BUG: FiberRuntime - undefined - please report an issue at https://github.com/Effect-TS/effect/issues
    at absurd (file:///Users/timsuchanek/code/expand/node_modules/effect/dist/esm/internal/fiberRuntime.js:79:9)
    at FiberRuntime.runLoop (file:///Users/timsuchanek/code/expand/node_modules/effect/dist/esm/internal/fiberRuntime.js:1048:11)
    at FiberRuntime.evaluateEffect (file:///Users/timsuchanek/code/expand/node_modules/effect/dist/esm/internal/fiberRuntime.js:684:27)
    at FiberRuntime.evaluateMessageWhileSuspended (file:///Users/timsuchanek/code/expand/node_modules/effect/dist/esm/internal/fiberRuntime.js:659:16)
    at FiberRuntime.drainQueueOnCurrentThread (file:///Users/timsuchanek/code/expand/node_modules/effect/dist/esm/internal/fiberRuntime.js:440:85)
    at Array.run (file:///Users/timsuchanek/code/expand/node_modules/effect/dist/esm/internal/fiberRuntime.js:1078:10)
    at MixedScheduler.starveInternal (file:///Users/timsuchanek/code/expand/node_modules/effect/dist/esm/Scheduler.js:73:17)
    at file:///Users/timsuchanek/code/expand/node_modules/effect/dist/esm/Scheduler.js:89:47
Error: BUG: FiberRuntime - undefined - please report an issue at https://github.com/Effect-TS/effect/issues
Error: BUG: FiberRuntime - undefined - please report an issue at https://github.com/Effect-TS/effect/issues
    at absurd (file:///Users/timsuchanek/code/expand/node_modules/effect/dist/esm/internal/fiberRuntime.js:79:9)
    at FiberRuntime.runLoop (file:///Users/timsuchanek/code/expand/node_modules/effect/dist/esm/internal/fiberRuntime.js:1048:11)
    at FiberRuntime.evaluateEffect (file:///Users/timsuchanek/code/expand/node_modules/effect/dist/esm/internal/fiberRuntime.js:684:27)
    at FiberRuntime.evaluateMessageWhileSuspended (file:///Users/timsuchanek/code/expand/node_modules/effect/dist/esm/internal/fiberRuntime.js:659:16)
    at FiberRuntime.drainQueueOnCurrentThread (file:///Users/timsuchanek/code/expand/node_modules/effect/dist/esm/internal/fiberRuntime.js:440:85)
    at Array.run (file:///Users/timsuchanek/code/expand/node_modules/effect/dist/esm/internal/fiberRuntime.js:1078:10)
    at MixedScheduler.starveInternal (file:///Users/timsuchanek/code/expand/node_modules/effect/dist/esm/Scheduler.js:73:17)
    at file:///Users/timsuchanek/code/expand/node_modules/effect/dist/esm/Scheduler.js:89:47"

**Comment by timsuchanek** [comment]
Already got feedback from @mikearnaldi that this is just a suboptiomal error message for the case when I'm passing `undefined` to an Effect.
