### ISSUE TITLE
Effect.if crashes when first arg is widened to `any`

### ISSUE THREAD

**Issue by alex-dixon** [Effect-TS/effect#2271]
### What version of Effect is running?

2.2.3

### What steps can reproduce the bug?

```typescript
import { Effect } from 'effect'
import { pipe } from 'effect/Function'

const data = undefined as any

pipe(
  Effect.if(data && typeof data?.foo === 'string', {
    onTrue: Effect.succeed(42),
    onFalse: Effect.fail('whoop'),
  }),
  Effect.runSync
)
```

### What do you see instead?

```
/code/node_modules/effect/src/internal/fiberRuntime.ts:124
  throw new Error(
        ^
Error: BUG: FiberRuntime - undefined - please report an issue at https://github.com/Effect-TS/effect/issues
Error: BUG: FiberRuntime - undefined - please report an issue at https://github.com/Effect-TS/effect/issues
    at absurd (/code/node_modules/effect/src/internal/fiberRuntime.ts:124:9)
    at FiberRuntime.runLoop (/code/node_modules/effect/src/internal/fiberRuntime.ts:1282:11)
    at FiberRuntime.evaluateEffect (/code/node_modules/effect/src/internal/fiberRuntime.ts:879:27)
    at FiberRuntime.start (/code/node_modules/effect/src/internal/fiberRuntime.ts:933:14)
    at /code/node_modules/effect/src/internal/runtime.ts:92:18
    at /code/node_modules/effect/src/internal/runtime.ts:250:45
    at ab (/code/node_modules/effect/src/internal/runtime.ts:126:44)
    at pipe (/code/node_modules/effect/src/Function.ts:652:14)
    at Object.<anonymous> (/code/scratch.ts:6:5)
    at Module._compile (node:internal/modules/cjs/loader:1376:14) {
  toJSON: [Function (anonymous)],
  toString: [Function (anonymous)],
  [Symbol(effect/Runtime/FiberFailure)]: Symbol(effect/Runtime/FiberFailure),
  [Symbol(effect/Runtime/FiberFailure/Cause)]: {
    _tag: 'Die',
    defect: Error: BUG: FiberRuntime - undefined - please report an issue at https://github.com/Effect-TS/effect/issues
        at absurd (/code/node_modules/effect/src/internal/fiberRuntime.ts:124:9)
        at FiberRuntime.runLoop (/code/node_modules/effect/src/internal/fiberRuntime.ts:1282:11)
        at FiberRuntime.evaluateEffect (/code/node_modules/effect/src/internal/fiberRuntime.ts:879:27)
        at FiberRuntime.start (/code/node_modules/effect/src/internal/fiberRuntime.ts:933:14)
        at /code/node_modules/effect/src/internal/runtime.ts:92:18
        at /code/node_modules/effect/src/internal/runtime.ts:250:45
        at ab (/code/node_modules/effect/src/internal/runtime.ts:126:44)
        at pipe (/code/node_modules/effect/src/Function.ts:652:14)
        at Object.<anonymous> (/code/scratch.ts:6:5)
        at Module._compile (node:internal/modules/cjs/loader:1376:14)
  },
  [Symbol(nodejs.util.inspect.custom)]: [Function (anonymous)]
}
```

**Comment by mikearnaldi** [comment]
why would this be a bug? you're passing `undefined` in a place that expects either an Effect or a Boolean.
