### ISSUE TITLE
Schema.pick using Schema.Class stop working when upgrading Schema to 0.64

### ISSUE THREAD

**Issue by steffanek** [Effect-TS/effect#2342]
### What version of Effect is running?

2.4.7

### What steps can reproduce the bug?

```ts
class Person extends Schema.Class<Person>("Person")({
  name: Schema.string,
}) {}

const eitherPersonName = Schema.decodeEither(Person.pipe(Schema.pick("name")))({
  name: "john",
});
console.log(eitherPersonName);
```

### What is the expected behavior?

I should get an `Either`

### What do you see instead?

```
./node_modules/.pnpm/@effect+schema@0.64.5_effect@2.4.7_fast-check@3.16.0/node_modules/@effect/schema/src/Schema.ts:2088
    throw new Error(`pick: cannot handle this kind of transformation`)
          ^
Error: pick: cannot handle this kind of transformation
    at self (/node_modules/.pnpm/@effect+schema@0.64.5_effect@2.4.7_fast-check@3.16.0/node_modules/@effect/schema/src/Schema.ts:2088:11)
    at pipeArguments (/node_modules/.pnpm/effect@2.4.7/node_modules/effect/src/Pipeable.ts:293:21)
    at pipe (/node_modules/.pnpm/@effect+schema@0.64.5_effect@2.4.7_fast-check@3.16.0/node_modules/@effect/schema/src/Schema.ts:6219:27)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Object.S (/node_modules/.pnpm/tsx@4.7.1/node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)

Node.js v20.3.0
```

### Additional information

I've upgraded `effect/schema` from `0.63.2` to `0.64.5` and Schema.pick stop working properly with Schema.Class.

**Comment by gcanti** [comment]
I can't repro, `@effect/schema@0.63.2` raises the same error.

Code:

```ts
import * as Schema from "@effect/schema/Schema"

class Person extends Schema.Class<Person>()({
  name: Schema.string
}) {}

const eitherPersonName = Schema.decodeEither(Person.pipe(Schema.pick("name")))({
  name: "john"
})
console.log(eitherPersonName)
```

Error:

```
    throw new Error(`pick: cannot handle this kind of transformation`)
          ^


Error: pick: cannot handle this kind of transformation
```

**Comment by steffanek** [comment]
@gcanti before I was using:
- @effect: 2.4.1
- @effect/schema: 0.63.2

**Comment by gcanti** [comment]
@steffanek yes, and I can't repro it using `@effect/schema: 0.63.2`. As stated above, I get the same error (`pick` has never worked with transformations, even before, and the Class API defines a transformation under the hood)

**Comment by steffanek** [comment]
gosh my bad @gcanti I rollbacked I was actually transforming the Class to a struct: `Person.struct` and .pick'ing from that.
