### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for '_op' in undefined

### ISSUE THREAD

**Issue by dilame** [Effect-TS/effect#2708]
### What version of Effect is running?

3.1.2

### What steps can reproduce the bug?

```ts
import {Effect, TestClock, Console, Schedule} from "effect"

const test = Effect.gen(function* () {
    const sleeps = yield* TestClock.sleeps();
    console.log(sleeps);

}).pipe(Effect.repeat(Schedule.addDelay(Schedule.forever, () => '1 second')))

Effect.runPromise(test)
```

### What do you see instead?

```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError: Cannot use 'in' operator to search for '_op' in undefined
    at runLoop (/Users/bowzee/WebstormProjects/sandbox/node_modules/effect/src/internal/fiberRuntime.ts:1292:20)
    at evaluateEffect (/Users/bowzee/WebstormProjects/sandbox/node_modules/effect/src/internal/fiberRuntime.ts:891:27)
    at start (/Users/bowzee/WebstormProjects/sandbox/node_modules/effect/src/internal/fiberRuntime.ts:945:14)
    at <anonymous> (/Users/bowzee/WebstormProjects/sandbox/node_modules/effect/src/internal/runtime.ts:92:18)
    at resolve (/Users/bowzee/WebstormProjects/sandbox/node_modules/effect/src/internal/runtime.ts:283:38)
    at new Promise (<anonymous>)
    at <anonymous> (/Users/bowzee/WebstormProjects/sandbox/node_modules/effect/src/internal/runtime.ts:278:3)
    at Module.<anonymous> (/Users/bowzee/WebstormProjects/sandbox/node_modules/effect/src/internal/runtime.ts:259:32)
    at <anonymous> (/Users/bowzee/WebstormProjects/sandbox/src/effect.ts:24:8)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25) {
  name: '(FiberFailure) TypeError',
  [Symbol(effect/Runtime/FiberFailure)]: Symbol(effect/Runtime/FiberFailure),
  [Symbol(effect/Runtime/FiberFailure/Cause)]: {
    _tag: 'Die',
    defect: TypeError: Cannot use 'in' operator to search for '_op' in undefined
        at runLoop (/Users/bowzee/WebstormProjects/sandbox/node_modules/effect/src/internal/fiberRuntime.ts:1292:20)
        at evaluateEffect (/Users/bowzee/WebstormProjects/sandbox/node_modules/effect/src/internal/fiberRuntime.ts:891:27)
        at start (/Users/bowzee/WebstormProjects/sandbox/node_modules/effect/src/internal/fiberRuntime.ts:945:14)
        at <anonymous> (/Users/bowzee/WebstormProjects/sandbox/node_modules/effect/src/internal/runtime.ts:92:18)
        at resolve (/Users/bowzee/WebstormProjects/sandbox/node_modules/effect/src/internal/runtime.ts:283:38)
        at new Promise (<anonymous>)
        at <anonymous> (/Users/bowzee/WebstormProjects/sandbox/node_modules/effect/src/internal/runtime.ts:278:3)
        at Module.<anonymous> (/Users/bowzee/WebstormProjects/sandbox/node_modules/effect/src/internal/runtime.ts:259:32)
        at <anonymous> (/Users/bowzee/WebstormProjects/sandbox/src/effect.ts:24:8)
        at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
  }
}

Node.js v21.4.0
```

### Additional information

I understand, that my code makes not too much sense, but i guess it should not lead to TypeError

**Comment by mikearnaldi** [comment]
To use `TestClock` you need to provide a `TestContext` like:

```ts
import {Effect, TestClock, TestContext, Schedule} from "effect"

const test = Effect.gen(function* () {
    const sleeps = yield* TestClock.sleeps();
    console.log(sleeps);

}).pipe(Effect.repeat(Schedule.addDelay(Schedule.forever, () => '1 second')))

Effect.runPromise(test.pipe(Effect.provide(TestContext.TestContext)))
```

The reason this is not tracked at the type level is because otherwise test implementations wouldn't be composable with app code so we opted for a fiber ref

**Comment by dilame** [comment]
Yes, i understand that i need to provide `TestContext` in order to use `TestClock`, i also understand that it is not tracked at type level, but the error in runtime doesn't provide a clear understanding of whats going wrong, is it intended?

**Comment by DScheglov** [comment]
> We can try to improve the error message but not sure we have enough info at runtime to make it nice

Is there any way to make this code fail at compile time? 
Without it, dependency injection works as a dynamic service locator and will cause heavy debugging.

**Comment by mikearnaldi** [comment]
> > We can try to improve the error message but not sure we have enough info at runtime to make it nice
> 
> Is there any way to make this code fail at compile time? Without it, dependency injection works as a dynamic service locator and will cause heavy debugging.

As explained it is like this intentionally. For typed dependencies you have Context, in this case we use a FiberRef to not have explicit types. If using the TestClock added a dependency to the type you would not be able to use it in place of production code.

**Comment by dilame** [comment]
> not sure we have enough info at runtime to make it nice

Something like "_Some of the required dependencies not found_" message would be better that `TypeError` at runtime anyway IMHO:)

And, BTW, maybe we could depend on `Clock` on type-level, and substitute it with `TestClock` when needed?

**Comment by fubhy** [comment]
Closing as stale. This was reported against an old Effect version and there is no current reproduction or maintainer-owned next step in the issue snapshot. If this still reproduces on the latest version, please open a new issue with an updated minimal reproduction.
