### ISSUE TITLE
BUG: FiberRuntime - {}

### ISSUE THREAD

**Issue by Verthon** [Effect-TS/effect#3544]
### What version of Effect is running?

3.7.0

### What steps can reproduce the bug?

Reproduction repo: https://github.com/Verthon/effect-react-repro

* install deps: `nvm use && npm i`
* run test command: `npm run test:unit`
* test should fail with output `BUG: FiberRuntime - {} - please report an issue at https://github.com/Effect-TS/effect/issues`

### What is the expected behavior?

No error BUG: FiberRuntime - {} - test should pass

### What do you see instead?

```bash
BUG: FiberRuntime - {} - please report an issue at https://github.com/Effect-TS/effect/issues

      10 |   };
      11 |   const get = () => {
    > 12 |     return Effect.runSync(services.localStorage.get('lang')).pipe(Option.getOrUndefined);
         |                   ^
      13 |   };
      14 |   return { set, get };
      15 | };

      at absurd (node_modules/effect/src/internal/fiberRuntime.ts:130:9)
      at FiberRuntime.absurd [as runLoop] (node_modules/effect/src/internal/fiberRuntime.ts:1329:11)
      at FiberRuntime.runLoop [as evaluateEffect] (node_modules/effect/src/internal/fiberRuntime.ts:893:27)
      at FiberRuntime.evaluateEffect [as start] (node_modules/effect/src/internal/fiberRuntime.ts:947:14)
      at start (node_modules/effect/src/internal/runtime.ts:92:18)
      at node_modules/effect/src/internal/runtime.ts:247:45
      at Object.runSync (node_modules/effect/src/internal/runtime.ts:126:44)
      at Object.runSync [as get] (src/useLocaleStorage.ts:12:19)
      at get (src/App.tsx:10:38)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:15486:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:20103:13)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21626:16)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:27465:14)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26599:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:26505:5)
      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:26473:7)
      at recoverFromConcurrentError (node_modules/react-dom/cjs/react-dom.development.js:25889:20)
      at performConcurrentWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:25789:22)
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at act (node_modules/react/cjs/react.development.js:2582:11)
      at node_modules/@testing-library/react/dist/act-compat.js:47:25
      at renderRoot (node_modules/@testing-library/react/dist/pure.js:180:26)
      at render (node_modules/@testing-library/react/dist/pure.js:271:10)
      at Object.<anonymous> (src/App.spec.tsx:16:9)
```

### Additional information

Hi, I have never used effect before, sorry if this is a silly mistake.
It only happens in the jest tests in the original codebase (react-native) app works properly, only tests output this error.

**Comment by fubhy** [comment]
This is not a bug with Effect but instead with your mocking here: https://github.com/Verthon/effect-react-repro/blob/main/src/App.spec.tsx#L8-L12

You are mocking `get` and `set` to return an object with a `pipe` property. This is not an Effect an therefore the Fiber runtime has no idea what to do with it. That's also why this is just failing in Jest, because that's where you are doing the mocking of course.

It's basically equivalent to doing this:

```ts
Effect.runSync("I am not an Effect")
```

Either way, I'd recommend to

a) Get familiar with the basics of Effect before diving into testing (you'll notice that once you are familiar with Effect, you'll not do any mocking but instead provide test implementations through dependency injection)

b) Start with anything else but Frontend when first getting your feet wet with Effect. Frontend (and thus also React) is probably the worst starting point for learning Effect because it's the least documented, least explored and generally most difficult place to start
