### ISSUE TITLE
Decoding default missing for "_tag" in Schema.TaggedError

### ISSUE THREAD

**Issue by relsunkaev** [Effect-TS/effect#3787]
### What version of Effect is running?

3.9.2

### What steps can reproduce the bug?

```ts
import { Schema } from "@effect/schema";
import { pipe } from "effect";

export class ExternalApiError extends Schema.TaggedError<ExternalApiError>()(
  "ExternalApiError",
  {
    status: Schema.Literal(400),
    code: Schema.Literal(1501),
    message: Schema.String,
  },
) {}

const response = {
  status: 400,
  code: 1501,
  message: "Resource not found",
};

const result = Effect.runSync(Schema.decodeUnknown(ExternalApiError)(response));

console.log(result);
```

### What is the expected behavior?

```bash
ExternalApiError: Resource not found
    at input (/Users/.../node_modules/@effect/schema/src/Schema.ts:8691:44)
    at decode (/Users/.../node_modules/@effect/schema/src/Schema.ts:4085:77)
    at a (/Users/.../node_modules/@effect/schema/src/ParseResult.ts:907:19)
    at <anonymous> (/Users/.../node_modules/@effect/schema/src/ParseResult.ts:345:12)
    at <anonymous> (/Users/.../node_modules/effect/src/Function.ts:181:18)
    at parser (/Users/.../node_modules/@effect/schema/src/ParseResult.ts:899:11)
    at <anonymous> (/Users/.../node_modules/@effect/schema/src/ParseResult.ts:532:5)
    at <anonymous> (/Users/.../node_modules/@effect/schema/src/Schema.ts:496:26)
    at <anonymous> (/Users/.../scripts/test.ts:77:68)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25) {
  status: 400,
  code: 1501,
  _tag: 'ExternalApiError'
}
```

### What do you see instead?

```bash
node:internal/modules/run_main:129
    triggerUncaughtException(
    ^

ParseError: (ExternalApiError (Encoded side) <-> ExternalApiError)
└─ Encoded side transformation failure
   └─ ExternalApiError (Encoded side)
      └─ ["_tag"]
         └─ is missing
```

### Additional information

Decoding using a TaggedError is very useful when working with API's that return errors in a non-standard way (200 HTTP status code with response json's status field set to 400 or something else). This way I can just decode using a union with the expected success response and map the error responses to the error channel.

**Comment by gcanti** [comment]
This is not a bug, the `_tag` field is intentionally required during decoding:

```ts
import { Schema } from "@effect/schema"

class ExternalApiError extends Schema.TaggedError<ExternalApiError>()(
  "ExternalApiError",
  {
    status: Schema.Literal(400),
    code: Schema.Literal(1501),
    message: Schema.String
  }
) {}

type Encoded = typeof ExternalApiError.Encoded
/*
type Encoded = {
    readonly message: string;
    readonly status: 400;
    readonly code: 1501;
    readonly _tag: "ExternalApiError"; // <= required
}
*/
```
