### ISSUE TITLE
using filter will break jsonSchema generation

### ISSUE THREAD

**Issue by ryskajakub** [Effect-TS/effect#3915]
### What version of Effect is running?

3.10.12

### What steps can reproduce the bug?

```
// file test.ts
import { JSONSchema, Schema } from 'effect';

const Number = Schema.Struct({
  number: Schema.Number.pipe(Schema.filter(a => a > 10 ? "a can't be higher than 10" : true) ),
})

console.log(JSONSchema.make(Number))
```
run: `tsx test.ts`

### What is the expected behavior?

printing: 
```
{
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  required: [ 'number' ],
  properties: { number: { type: 'number' } },
  additionalProperties: false
}
```

### What do you see instead?

```
Error: Missing annotation
at path: ["number"]
details: Generating a JSON Schema for this schema requires a "jsonSchema" annotation
schema (Refinement): { number | filter }
    at go (/home/kuba/bighub/eva/egd-eva-api/backend/node_modules/effect/src/JSONSchema.ts:579:15)
    at go (/home/kuba/bighub/eva/egd-eva-api/backend/node_modules/effect/src/JSONSchema.ts:519:13)
    at schema (/home/kuba/bighub/eva/egd-eva-api/backend/node_modules/effect/src/JSONSchema.ts:214:22)
    at <anonymous> (/home/kuba/bighub/eva/egd-eva-api/backend/test.ts:8:24)
    at Object.<anonymous> (/home/kuba/bighub/eva/egd-eva-api/backend/test.ts:8:36)
    at Module._compile (node:internal/modules/cjs/loader:1467:14)
    at Object.transformer (/home/kuba/bighub/eva/egd-eva-api/backend/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186)
    at Module.load (node:internal/modules/cjs/loader:1282:32)
    at Module._load (node:internal/modules/cjs/loader:1098:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)

```

**Comment by gcanti** [comment]
This is the intended behavior, a refinement **requires** a JSON schema annotation. See this for more details: https://effect.website/docs/schema/json-schema/#refinements

For instance:

```ts
import { JSONSchema, Schema } from "effect"

const Number = Schema.Struct({
  number: Schema.Number.pipe(
    Schema.filter((a) => (a > 10 ? "a can't be higher than 10" : true), {
      jsonSchema: {
        maximum: 10
      }
    })
  )
})

console.log(JSONSchema.make(Number))
/*
Output:
{
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  required: [ 'number' ],
  properties: { number: { type: 'number', maximum: 10 } },
  additionalProperties: false
}
*/
```

If you are not interested in setting a specific json schema annotation you can pass an empty annotation:

```ts
import { JSONSchema, Schema } from "effect"

const Number = Schema.Struct({
  number: Schema.Number.pipe(
    Schema.filter((a) => (a > 10 ? "a can't be higher than 10" : true), {
      jsonSchema: {} // empty
    })
  )
})

console.log(JSONSchema.make(Number))
/*
Output:
{
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  required: [ 'number' ],
  properties: { number: { type: 'number' } },
  additionalProperties: false
}
*/
```

**Comment by ryskajakub** [comment]
I got the point. in this case I could imagine:
1) making the `jsonSchema` required for filter
2) having another type parameter in Schema, that would indicate which capabilities are available. In case `jsonSchema` is not provided for all filters, `JSONSchema.make` would not typecheck
