### ISSUE TITLE
HttpClient retryTransient ignoring timeouts

### ISSUE THREAD

**Issue by StefanTheWiz** [Effect-TS/effect#3999]
### What version of Effect is running?

3.10.16

### What steps can reproduce the bug?

```ts
import { Effect, Logger, LogLevel, Schedule } from 'effect';
import { FetchHttpClient } from '@effect/platform';
import {
  filterStatusOk,
  followRedirects,
  HttpClient,
  retry, retryTransient,
  tapRequest,
  transformResponse
} from '@effect/platform/HttpClient';
import { isHttpClientError } from '@effect/platform/HttpClientError';


const httpClient = Effect.gen(function*() {
  return (yield* HttpClient).pipe(
    tapRequest((request) => Effect.logDebug(`>>>> ${request.method} ${request.url}`)),
    filterStatusOk,
    followRedirects(3),
    transformResponse((r) =>
      r.pipe(
        Effect.tap((_) => Effect.logDebug('transformResponse')),
        Effect.timeout('1 second')
      )
    ),
    retryTransient({ // this doesn't work
      schedule: Schedule.jittered(Schedule.exponential("1 second")),
      times: 3,
    }),
    /*
    retry({ // this works because it uses 'until' instead of while and inverted some conditions
      until: (error) => isHttpClientError(error) &&
        ((error._tag === "RequestError" && error.reason !== "Transport") ||
          error._tag === "ResponseError" && error.response.status < 429),
      schedule: Schedule.jittered(Schedule.exponential("1 second")),
      times: 3,
    }),
     */
  );
})

const program = (url: string) => Effect.gen(function*() {
  const client = yield* httpClient;
  return yield* client.head(url);
}).pipe(
  Effect.provide(FetchHttpClient.layer),
  Effect.provide(Logger.pretty),
  Effect.provide(Logger.minimumLogLevel(LogLevel.Debug)),
  Effect.catchAllCause(cause => Effect.logError(cause)),
  Effect.scoped, // Ensure request is aborted if the program is interrupted
)

const testURLs = [
  'https://pentafox.co.uk', // 30-50 seconds; should be tried 3x (lib only tries once)
  "https://asdfsgdg.co.uk", // doesn't exist; should be tried 3x (lib works as expected)
  "https://jsonplaceholder.typicode.com/posts/1", // successful; NOT retried
  "https://jsonplaceholder.typicode.com/non-existing-page", // 404; NOT retried
];
for (const url of testURLs) {
  console.log('result', await Effect.runPromise(program(url)));
}
```

### What is the expected behavior?

the first URL should be retried 3x, like it does for `https://asdfsgdg.co.uk`

```
      [00:46:05.084] DEBUG (#4): >>>> HEAD https://asdfsgdg.co.uk
      [00:46:05.089] DEBUG (#4): Fiber terminated with an unhandled error
        RequestError: Transport error (HEAD https://asdfsgdg.co.uk)

      [00:46:06.028] DEBUG (#6): >>>> HEAD https://asdfsgdg.co.uk
      [00:46:06.031] DEBUG (#6): Fiber terminated with an unhandled error
        RequestError: Transport error (HEAD https://asdfsgdg.co.uk)

      [00:46:08.019] DEBUG (#8): >>>> HEAD https://asdfsgdg.co.uk
      [00:46:08.025] DEBUG (#8): Fiber terminated with an unhandled error
        RequestError: Transport error (HEAD https://asdfsgdg.co.uk)
       
      [00:46:11.443] DEBUG (#10): >>>> HEAD https://asdfsgdg.co.uk
      [00:46:11.456] DEBUG (#10): Fiber terminated with an unhandled error
        RequestError: Transport error (HEAD https://asdfsgdg.co.uk)

      timestamp=2024-11-26T00:46:11.460Z level=ERROR fiber=#3 cause="RequestError: Transport error (HEAD https://asdfsgdg.co.uk)

      result undefined
```

### What do you see instead?

lib only tries once

```
      [00:46:03.936] DEBUG (#1): >>>> HEAD https://pentafox.co.uk
      timestamp=2024-11-26T00:46:05.017Z level=ERROR fiber=#0 cause="TimeoutException: Operation timed out before the specified duration of '1s' elapsed
          at Object.timeoutExceptionFromDuration (/project/node_modules/effect/src/internal/core.ts:2338:3)
          at /project/node_modules/effect/src/internal/effect/circular.ts:505:27"

      result undefined
```

### Additional information

The issue is here: https://github.com/Effect-TS/effect/blob/42c4ce6f8d8c7d847e97757650a8ad9419a829d7/packages/platform/src/internal/httpClient.ts#L591-L594

I believe it needs to be changed to retry "until a transient error is encountered", however I'm open to suggestions as well
```ts
retry({ 
      until: (error) => isHttpClientError(error) &&
        ((error._tag === "RequestError" && error.reason !== "Transport") ||
          error._tag === "ResponseError" && error.response.status < 429),
      // .....
    }),
```

**Comment by tim-smart** [comment]
We could consider a TimeoutException a transient failure, but `retryTransient` only considers the http domain errors at the moment.

**Comment by StefanTheWiz** [comment]
Thanks!
